Invento-A Pharmacy Management_final/Uphar 2/Chemist_Master/urls.py
from django.urls import path
from Chemist_Master.views import SK_Create_Pdf,SK_View_Bills,Dashboard,DeleteProduct,EditProduct,ProductListView,order_medicine,chemist_index,chemist_signup,chemist_signin,query,Uploaded_Medi,update_med,delete_med,logout,forgot_pass,otpcheck,newpassword,order_medicine

urlpatterns = [
    # signin,signup,indexpage
    path('signin/',chemist_signin,name="ch_signin"),
    path('signup/',chemist_signup,name="ch_signup"),
    path('',chemist_index,name="ch_index"),
    #Chemist interactions with medicines
    path('Uploaded_Medi/',Uploaded_Medi,name='Uploaded_Medi'),
    path('update_med/<int:id>',update_med,name='update_med'),
    path('delete_med/<int:id>',delete_med,name='delete_med'),
    path('order-medicine/',order_medicine,name='order-medicine'),
    path('productlist/', ProductListView, name='ProductListView'),
    path('dashboard/', Dashboard, name='Dashboard'),
    path('query/', query, name='query'),

    path('deleteproduct/<int:id>', DeleteProduct, name='deleteproduct'),
    path('editproduct/<int:id>', EditProduct, name='editproduct'),
    
    #Logout
    path('logout/',logout,name='logout'),
    
    # Forgot Password
    path('forgot_pass/',forgot_pass,name="forgotpass"),
    path('otpcheck/',otpcheck,name="otpcheck"),
    path('newpassword/',newpassword,name="newpassword"),
    path('View_Bills/<str:ids>', SK_View_Bills, name='SK_View_Bills'),
    path('SK_create_pdf/<str:dt>',SK_Create_Pdf, name='sk_create_pdf'),

    
]

Invento-A Pharmacy Management_final/Uphar 2/Uphar/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(('User_Master.urls','user'))),
    path('guide/',include(('guide.urls','guide'))),
    path('med/',include(('med.urls','med'))),
    path('Chemist_Master/',include(('Chemist_Master.urls','chemist'))),
]

Invento-A Pharmacy Management_final/Uphar 2/med/urls.py
from django.urls import path
from med import views
from .views import Search
urlpatterns = [
  
    path('add/', views.medi,name='add'),
    path('show/',views.show1,name='show'),
    path("search/<str:para>/",views.show, name="profilesearch"),
    path("search/", Search.as_view(), name="searchpage"),
    path('update/<int:id>', views.update),  
    path('delete/<int:id>', views.destroy), 
]

Invento-A Pharmacy Management_final/Uphar 2/Chemist_Master/models.py
from django.db import models


# Chemist Details
class ChemistRegister(models.Model):
    cid=models.EmailField(max_length=50,verbose_name='Email')
    chemistpwd=models.CharField(max_length=20,verbose_name='Password')
    chemistfname=models.CharField(max_length=20,default='',verbose_name='First_Name')
    chemistmname=models.CharField(max_length=20,default='',verbose_name='Middle_Name')
    chemistlname=models.CharField(max_length=20,default='',verbose_name='Last_Name')
    chemistaddress=models.CharField(max_length=20,default='',verbose_name='Address')
    chemistcity=models.CharField(max_length=20,default='',verbose_name='City')
    chemistarea=models.CharField(max_length=20,default='',verbose_name='Area')
    chemistpincode=models.IntegerField(default='',verbose_name='Pincode')
    chemistcontactno=models.IntegerField(default='',verbose_name='Contact_No')
    chemistphoto = models.FileField(upload_to = 'upload',verbose_name='store certificate',null=True,blank=True)
    forgot_pass = models.CharField('Write your password hint',max_length=100,default='')
    def __str__(self):
        return self.cid


## ------changes--------##
class StoreDetails(models.Model):
    StoreName = models.CharField(max_length = 50,blank = True)
    PersonName = models.CharField(max_length = 50,blank = True)
    Contact = models.IntegerField(blank = True)
    email = models.EmailField(blank = True, default="", max_length=150)
    password = models.CharField(max_length = 50)
    add1 = models.TextField(default="")

    def __str__(self):
        return self.StoreName


class StockDetails(models.Model):
    productName = models.CharField(max_length = 50,blank = True)
    quantity = models.IntegerField()
    price = models.FloatField()

    def __str__(self):
        return self.productName

class ProductDetails(models.Model):
    store_person = models.ForeignKey('ChemistRegister',on_delete=models.CASCADE, null=True)
    productname = models.CharField(max_length = 50,default="")
    productquantity = models.IntegerField()
    date = models.DateField(auto_now=False,blank=True,null=True)
    status = models.BooleanField(default=False)
    isDeny = models.BooleanField(default=False)
    Bills_id = models.CharField(max_length = 200,default="",null=True,blank=True)

    def __str__(self):
        return self.productname


class SK_Bills(models.Model):
    store_person = models.ForeignKey('ChemistRegister',on_delete=models.CASCADE, null=True)
    Bill_No = models.CharField(max_length = 200,default="")
    pd_nm = models.CharField(max_length = 200,default="")
    pd_price = models.FloatField(default=0.0)
    pd_qty = models.IntegerField(default=0)
    pd_tot = models.FloatField(default=0.0)
    date_data = models.DateField(auto_now=False,blank=True,null=True)
    
    def __str__(self):
        return self.Bill_No

Invento-A Pharmacy Management_final/Uphar 2/User_Master/models.py
from django.db import models
from guide.models import guides

# User Details
class UserRegister(models.Model):
    uid=models.EmailField(max_length=50,verbose_name='Email',unique="True")
    userpwd=models.CharField(max_length=20,verbose_name='Password')
    userfname=models.CharField(max_length=20,default='',verbose_name='First_Name')
    usermname=models.CharField(max_length=20,default='',verbose_name='Middle_Name')
    userlname=models.CharField(max_length=20,default='',verbose_name='Last_Name')
    useraddress=models.CharField(max_length=20,default='',verbose_name='Address')
    usercity=models.CharField(max_length=30,default='',verbose_name='City')
    userarea=models.CharField(max_length=20,default='',verbose_name='Area')
    userpincode=models.IntegerField(default='',verbose_name='Pincode')
    usercontactno=models.IntegerField(default='',verbose_name='Contact_No')
    forgot_pass = models.CharField('Write your password hint',max_length=100,default='')

    def __str__(self):
        return self.uid

# Cart Models
class cart(models.Model):
    user = models.ForeignKey(UserRegister,on_delete=models.CASCADE)
    medicine = models.ForeignKey(guides,on_delete=models.CASCADE)
    quantity = models.IntegerField()
    status = models.BooleanField(default=False)
    added_on =models.DateTimeField(auto_now_add=True,null=True)
    update_on = models.DateTimeField(auto_now=True,null=True)

    def __str__(self):
        return self.medicine.mname

class UserQuery(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField(max_length=200,default='')
    subject= models.CharField(default='',max_length=100)
    message = models.CharField(default='',max_length=500)

    def __str__(self):
        return self.name

Invento-A Pharmacy Management_final/Uphar 2/Chemist_Master/forms.py
from django import forms
from Chemist_Master.models import ChemistRegister
from  guide.models import guides

class ChemistRegisterform(forms.ModelForm):
    class Meta:
        model=ChemistRegister
        fields='__all__'

class guideForm(forms.ModelForm):
    class Meta:
        model = guides
        fields = "__all__"

Invento-A Pharmacy Management_final/Uphar 2/Chemist_Master/views.py
from django.shortcuts import render,redirect
from django.http import request,HttpResponseRedirect,HttpResponse
from Chemist_Master.models import *
from User_Master.models import *
from med.models import Medicine
from med.forms import MedicineForm
from Chemist_Master.forms import ChemistRegisterform,guideForm
from guide.models import guides
from django.core.paginator import Paginator
from datetime import date
import random
#email
import smtplib, ssl,pandas 
from .models import SK_Bills,ChemistRegister

from io import BytesIO
from django.http import HttpResponse
from django.template.loader import get_template

from xhtml2pdf import pisa

from django.http import HttpResponse
from django.views.generic import View
from plotly.offline import plot
from plotly.graph_objs import Scatter

import pdfkit

#Chemist signin page
def chemist_signin(request):
    if request.method=="POST":
        print(request.POST['cid'])
        try:
            m = ChemistRegister.objects.get(cid=request.POST['cid'])
            if m.chemistpwd == request.POST['chemistpwd']:
                request.session['user'] = m.cid
                return redirect('chemist:ch_index')
            else:
                return render(request,'error.html')
        except:
            return render(request,'error.html')
    return render(request,'chemist_signin1.html')

# Showing uploaded medicines by chemist
def Uploaded_Medi(request):
    
    if 'user' in request.session:
        med = guides.objects.all()
        paginator = Paginator(med, 5) # Show 10 medicines per page.
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        return render(request,'test.html',{'med':med,'page_obj': page_obj})
    else:
        return redirect('chemist:ch_signin')

            
  # Update medicine {done by chemist}   
def update_med(request,id):
    if 'user' in request.session:
        medi = guides.objects.get(id=id)  
        form = guideForm(request.POST or None, instance = medi)  
        if form.is_valid():  
            form.save()  
            return redirect('chemist:Uploaded_Medi')
        return render(request,'edit.html', {'medi': medi}) 
    else:
        return redirect('chemist:ch_signin')
 
# delete medicine{done by chemist}
def delete_med(request,id):
    med = guides.objects.get(id=id)
    med.delete()
    return redirect('chemist:Uploaded_Medi')
    
# Chemist module home page
def chemist_index(request):
    if 'user' in request.session:
        return render(request,'chemist_index.html')
    else:
        return redirect('chemist:ch_signin')
        
# chemist signup
def chemist_signup(request):
    obj=ChemistRegisterform(request.POST,request.FILES)
    if obj.is_valid():
        obj.save()
        return redirect('chemist:ch_signin')
    return render(request,'chemist_signup.html',{'obj':obj})

#chemist logout
def logout(request):
    if 'user' in request.session:
        del request.session['user']
        return redirect('chemist:ch_signin')
    else:
        return redirect('chemist:ch_signin')
#chemist forgotpassword

def forgot_pass(request):
    email = request.POST.get('email')
    request.session['username'] = email
    if email == None:
        return render(request,'email.html')
        
    print(email)
    otp = ''
    rand = random.choice('0123456789')
    rand1 = random.choice('0123456789')
    rand2 = random.choice('0123456789')
    rand3 = random.choice('0123456789')
    otp = rand + rand1 + rand2 + rand3
    print(otp)
    request.session['otp'] = otp


    port = 465
    context = ssl.create_default_context()
    server = smtplib.SMTP_SSL("smtp.gmail.com",port,context=context)
    server.login("mailtesting681@gmail.com","mailtest@123")
    server.sendmail("mailtesting681@gmail.com",email,otp)
    server.quit()
    return redirect('chemist:otpcheck')
    return render(request,'email.html')

def otpcheck(request):
    if request.session.has_key('otp'):
        otp = request.session['otp']
        try:
            otpobj = request.POST.get('otp')
            if otpobj == None:
                return render(request,'otp.html')
            if otp == request.POST.get('otp'):
                return redirect('chemist:newpassword')
            else:
                return HttpResponse("<a href = ''>Wrong OTP Entered.</a>")
        except:
            return redirect('chemist:ch_signin')
    return render(request,'otp.html')

def newpassword(request):
    new_pass = request.POST.get('password')
    if request.method == 'POST':
        obj = ChemistRegister.objects.get(cid = request.session['username'])
        obj.chemistpwd = new_pass
        obj.save()
        return redirect('chemist:ch_signin')
    return render(request,'forgotpassword.html')

def order_medicine(request):
    username = request.session['user']
    print(username)
    store = ChemistRegister.objects.get(cid=username)
    prods = StockDetails.objects.all()
    if request.POST:
        pro_data = request.POST['productname']
        pro_qty = request.POST['productquantity']
        prod_date = request.POST['data']
        obj = ProductDetails()
        obj.store_person = store
        pro_nm = StockDetails.objects.get(id=int(pro_data))
        obj.productname = pro_nm.productName
        obj.productquantity = pro_qty
        obj.date = prod_date
        obj.save()
        return redirect('chemist:ProductListView')
    return render(request, 'store/addproduct.html', {'username': username, 'prods': prods})

def query(request):
      if request.POST:
        obj = UserQuery()
        obj.name=request.POST['name']
        obj.email=request.POST['email']
        obj.subject=request.POST['subject']
        obj.message=request.POST['message']
        obj.save()
        return redirect('chemist:ch_index') 
def ProductListView(request):
    if request.session.has_key('user'):
        username = request.session['user']
        store = ChemistRegister.objects.get(cid=username)
        model = ProductDetails.objects.filter(store_person=store)
        return render(request, 'store/productlist.html', {'data': model, 'username': username})
    else:
        return redirect('chemist:ch_signin')


def DeleteProduct(request, id):
    if request.session.has_key('user'):
        username = request.session['user']
        obj = ProductDetails.objects.get(id=id)
        obj.delete()
        return redirect('chemist:ProductListView')
    else:
        return redirect('chemist:ch_signin')


def EditProduct(request, id):
    if request.session.has_key('user'):
        username = request.session['user']
        model = ProductDetails.objects.get(id=id)
        # form = ProductDetailsForm(request.POST, instance=model)
        if request.POST:
            model.productname=request.POST['productname']
            model.productquantity=request.POST['productquantity']
            model.save()
            return redirect('chemist:ProductListView')
        return render(request, 'store/editproduct.html', {'data': model, 'username': username})
    else:
        return redirect('chemist:ch_signin')

class ProductViewData():
    def __init__(self, name, date, status):
        self.name = name
        self.date = date
        self.status = status

def getStatusInStr(isStatus, isDeny):
    if isStatus == True:
        return "Accepted"
    else:
        if isDeny == True:
            return "Denied"
        return "Pending"

def Dashboard(request):
    if request.session.has_key('user'):
        username = request.session['user']
        store = ChemistRegister.objects.get(cid=username)

        pdBill = SK_Bills.objects.filter(store_person=store)
        Bcount = 0
        bset = set()
        for i in pdBill:
            bset.add(str(i.Bill_No))

        print(bset)
        bset = list(bset)
        # bset.sort()
        print(bset)

        model = ProductDetails.objects.filter(store_person=store).count()
        today_stock = ProductDetails.objects.filter(
            store_person=store, date=date.today())
        qty = 0
        today_date = date.today
        print(today_date)

        acceptedData = ProductDetails.objects.filter(store_person=store)
        acceptedData = map(lambda product: ProductViewData(getattr(product, 'productname'), getattr(product, 'date'), getStatusInStr(getattr(product, 'status'), getattr(product, 'isDeny'))), acceptedData)

        for i in today_stock:
            qty += i.productquantity
        return render(request, 'store/dashboard.html', {'acceptedData' : acceptedData, 'bset': bset, 'Bcount': len(bset), 'data': model, 'total': qty, 'date': today_date, 'username': username})
    else:
        return redirect('chemist:ch_signin')

def SK_View_Bills(request, ids):
    print(ids)
    pdBill = SK_Bills.objects.filter(Bill_No=ids)
    tot = 0.0
    date = ""
    sperson = ''
    for i in pdBill:
        date = i.date_data
        sperson = i.store_person
        tot += float(i.pd_tot)
    return render(request, 'store/SK_Order_Bill.html', {'billNo': ids, 'sperson': sperson, 'ddate': date, 'tot': tot, 'BillDes': pdBill})

def render_to_pdf(template_src, context_dict={}):
    template = get_template(template_src)
    html = template.render(context_dict)
    result = BytesIO()
    pdf = pisa.pisaDocument(BytesIO(html.encode("ISO-8859-1")), result)
    if not pdf.err:
        return HttpResponse(result.getvalue(), content_type='application/pdf')
    return None



def SK_Create_Pdf(request, dt):
    if request.session.has_key('user'):
        # username = request.session['user']
        pdBill = SK_Bills.objects.filter(Bill_No=dt)
        for i in pdBill:
            k=i.store_person
        store = ChemistRegister.objects.get(cid=k)

        tot = 0.0
        date = ""
        sperson = ''
        for i in pdBill:
            date = i.date_data
            sperson = i.store_person
            tot += float(i.pd_tot)

        Order_Data = {}

        obj_data = SK_Bills.objects.filter(Bill_No=dt)

        prod_price = 0

Invento-A Pharmacy Management_final/Uphar 2/Chemist_Master/templates/chemist_signin1.html
{% load static %}

<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>َLogin</title>
    <link rel="stylesheet" href="{% static 'signin1.css' %}">
  </head>
  <body>

<form class="box"  method="POST">
  {% csrf_token %}
  <h1>Chemist Login</h1>
  <input type="text" name="cid" value="{{ cid }}" placeholder="Email">
  <input type="password" name="chemistpwd" value="{{ chemistpwd }}" placeholder="Password">
  <input type="submit" name="" href="/med/show/" value="Sign In">
  <a href="{% url 'chemist:ch_signup' %}">Register</a>

<br>
<div class="hr"></div>
<div class="foot-lnk">
                    <p style="color: white;">Visit our page?</p><a href="{% url 'user:index' %}" style="color: teal;" >click here </a></div>



</form>
</body>
</html>

Invento-A Pharmacy Management_final/Uphar 2/Chemist_Master/templates/chemist_signup.html
{% load static %}
<html>
                <head>
                
                        <link rel="stylesheet" type="text/css" href="{% static 'css/register.css' %}">
        
                </head>
    <body>
            <form  method="POST" enctype="multipart/form-data" autocomplete="off">
                {% csrf_token %}
                
                    <div class="login-wrap">
                        <div class="login-html">
   
                                <input id="tab-1" type="radio" name="tab" class="sign-in" checked><label for="tab-1" class="tab">Sign up</label>
                                
                                <div class="login-form">

                                        <div class="sign-up-html">
                                                <div class="group">
                                                       
                                                        <label for="user" type="Email" class="label">Email</label>
                                                        <input id="id_cid" type="text" name="cid" class="input" value="{{ cid }}">
                                                </div>
                                                <div class="group">
                                                        <label for="pass" type="password" class="label" data-type="password">Password</label>
                                                        <input id="id_chemistpwd" type="password" name="chemistpwd" class="input" value="{{ chemistpwd }}">
                                                        
                                                </div>
                                                <div class="group">
                                                        <label for="pass" type="text" class="label" data-type="password">Password hint</label>
                                                        <input id="id_userpwd" type="text" name="forgot_pass" class="input" value="{{ forgot_pass }}">
                                                        
                                                </div>
                                                <div class="group">
                                                        <label for="pass" class="label">First Name</label>
                                                        <input id="id_chemistfname" type="text" name="chemistfname" class="input" value="{{ chemistfname }}">
                                                </div>
                                                <div class="group">
                                                        <label for="pass" class="label">Middle Name</label>
                                                        <input id="id_chemistmname" type="text" name="chemistmname" class="input" value="{{ chemistmname }}">
                                                </div>
                                                <div class="group">
                                                        <label for="pass" class="label">Last Name</label>
                                                        <input id="id_chemistlname" type="text" name="chemistlname" class="input" value="{{ chemistlname }}">
                                                </div>
                                                <div class="group">
                                                        <label for="pass" class="label">Address</label>
                                                        <input id="id_chemistaddress" type="text" name="chemistaddress" class="input" value="{{ chemistaddress }}">
                                                </div>
                                                <div class="group">
                                                        <label for="pass" class="label">City</label>
                                                        <input id="id_chemistcity" type="text" name="chemistcity" class="input" value="{{ chemistcity }}">
                                                </div>
                                                <div class="group">
                                                        <label for="pass" class="label">Area</label>
                                                        <input id="id_chemistarea" type="text" name="chemistarea" class="input" value="{{ chemistarea }}">
                                                </div>
                                                <div class="group">
                                                        <label for="pass" class="label">Pincode</label>
                                                        <input id="id_chemistpincode" type="text" name="chemistpincode" class="input" value="{{ chemistpincode }}">
                                                </div>
                                                <div class="group">
                                                        <label for="pass" class="label">Contact_No</label>
                                                        <input id="id_chemistcontactno" type="text" name="chemistcontactno" class="input" value="{{ chemistcontactno }}">
                                                </div>
                                                <div class="group">
                                                        <label for="pass" class="label">Store Certificate</label>
                                                        <input id="id_chemistphoto" type="file" name="chemistphoto" class="input" value="{{ chemistphoto }}">
                                                </div>
                                                <div class="group">
                                                        <input type="submit" class="button" value="Sign Up"><a href="{% url 'chemist:ch_signup' %}"></a>
                                                </div>
                                                <div class="hr"></div>
                                                <div class="foot-lnk">
                                                        <label for="tab-1"><a href="{% url 'chemist:ch_signin' %}">Already Member?</a>
                                                </div>
                                        </div>
                                </div>
                        </div>
                </div>     
        
            </form>
    </body>
</html>

Invento-A Pharmacy Management_final/Uphar 2/Chemist_Master/templates/email.html
<html>
    <body>
        <h1>{{otp}}</h1>
        <form method="POST">
            {% csrf_token %}
            <input type="email" id="id_user_name" name="email" value="{{ email }}" placeholder="Enter Email Id">
            <br>
            <button type="submit">Send Otp</button>
        </form>
    </body>
</html>

Invento-A Pharmacy Management_final/Uphar 2/Chemist_Master/templates/forgotpassword.html
<html>
    <body>
        <form method="POST">
            {% csrf_token %}
            <input type="password" id="id_password" name="password" placeholder="Enter New Password" value="{{ password }}">
            <br>
            <button type="submit">Reset</button>
        </form>
    </body>
</html>

Invento-A Pharmacy Management_final/Uphar 2/Chemist_Master/templates/otp.html
<html>
    <body>
        <form method="POST">
            {% csrf_token %}
            <input type="number" id="id_otp" name="otp" value="{{ otp }}" placeholder="Enter OTP">
            <br>
            <button type="submit">Submit</button>
        </form>
    </body>
</html>