Invento-A Pharmacy Management_final/Uphar 2/Uphar/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(('User_Master.urls','user'))),
    path('guide/',include(('guide.urls','guide'))),
    path('med/',include(('med.urls','med'))),
    path('Chemist_Master/',include(('Chemist_Master.urls','chemist'))),
]

Invento-A Pharmacy Management_final/Uphar 2/User_Master/urls.py
from django.urls import path
from  User_Master import views


urlpatterns = [

    #User Signin,Signup,Logout,IndexpagenIndexpage1
    path('signin/',views.signin,name="signin"),
    path('signup/',views.signup,name="signup"),
    path('logout/',views.logout,name='logout'),
    path('',views.index,name="index"),
    path('Userindex/',views.index1,name="Userindex"),

    #User search function
    path('search/',views.search, name = "search"),
    
    #User Forgot Password
    path('forgot_pass/',views.forgot_pass,name="forgotpass"),
    path('otpcheck/',views.otpcheck,name="otpcheck"),
    path('newpassword/',views.newpassword,name="newpassword"),
    
    #User Add to Cart
    path('cart/',views.add_to_cart, name="cart"),
    path('getcartData/',views.get_cart_data, name = "cartData"),
    path('changedata/',views.change_quan,name="changeData"),
    
    # -------------changes------
    path('adminDashboard/', views.AdminDashboard, name='adminDashboard'),
    path('storeview/<int:id>', views.viewstore, name='viewstore'),
    path('storeedit/<int:id>', views.editstore, name='editstore'),
    path('storedelete/<int:id>', views.deletestore, name='deletestore'),
    path('Confirm_Orders/', views.Confirm_Orders, name="confirm_order"),

    path('accept_data/<int:sk>/<int:id>/', views.accepteddata, name='accept_data'),
    path('denied_data/<int:sk>/<int:id>/', views.denieddata, name='denied_data'),    
    path('billdata/<str:dt>', views.billdata, name='billdata'),
    path('create_pdf/<str:dt>', views.Create_Pdf, name='create_pdf'),
    path('createGraph/', views.createGraph, name="createGraph"),
    path('allbill/',views.allbill,name='allbill')

]

Invento-A Pharmacy Management_final/Uphar 2/med/urls.py
from django.urls import path
from med import views
from .views import Search
urlpatterns = [
  
    path('add/', views.medi,name='add'),
    path('show/',views.show1,name='show'),
    path("search/<str:para>/",views.show, name="profilesearch"),
    path("search/", Search.as_view(), name="searchpage"),
    path('update/<int:id>', views.update),  
    path('delete/<int:id>', views.destroy), 
]

Invento-A Pharmacy Management_final/Uphar 2/User_Master/models.py
from django.db import models
from guide.models import guides

# User Details
class UserRegister(models.Model):
    uid=models.EmailField(max_length=50,verbose_name='Email',unique="True")
    userpwd=models.CharField(max_length=20,verbose_name='Password')
    userfname=models.CharField(max_length=20,default='',verbose_name='First_Name')
    usermname=models.CharField(max_length=20,default='',verbose_name='Middle_Name')
    userlname=models.CharField(max_length=20,default='',verbose_name='Last_Name')
    useraddress=models.CharField(max_length=20,default='',verbose_name='Address')
    usercity=models.CharField(max_length=30,default='',verbose_name='City')
    userarea=models.CharField(max_length=20,default='',verbose_name='Area')
    userpincode=models.IntegerField(default='',verbose_name='Pincode')
    usercontactno=models.IntegerField(default='',verbose_name='Contact_No')
    forgot_pass = models.CharField('Write your password hint',max_length=100,default='')

    def __str__(self):
        return self.uid

# Cart Models
class cart(models.Model):
    user = models.ForeignKey(UserRegister,on_delete=models.CASCADE)
    medicine = models.ForeignKey(guides,on_delete=models.CASCADE)
    quantity = models.IntegerField()
    status = models.BooleanField(default=False)
    added_on =models.DateTimeField(auto_now_add=True,null=True)
    update_on = models.DateTimeField(auto_now=True,null=True)

    def __str__(self):
        return self.medicine.mname

class UserQuery(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField(max_length=200,default='')
    subject= models.CharField(default='',max_length=100)
    message = models.CharField(default='',max_length=500)

    def __str__(self):
        return self.name

Invento-A Pharmacy Management_final/Uphar 2/User_Master/forms.py
from django import forms
from User_Master.models import UserRegister,UserQuery

class UserRegisterForm(forms.ModelForm):
    class Meta:
        model=UserRegister
        fields='__all__'

class UserQueryForm(forms.ModelForm):
    class Meta:
        model=UserQuery
        fields='__all__'
    

Invento-A Pharmacy Management_final/Uphar 2/User_Master/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.http import request,HttpResponseRedirect,HttpResponse,JsonResponse
from django.contrib.auth import update_session_auth_hash
from django.contrib import messages
from django.db.models import Q

from .models import UserRegister,cart,UserQuery
from .forms import UserRegisterForm,UserQueryForm
from Chemist_Master.models import StoreDetails,ProductDetails,StockDetails,SK_Bills,ChemistRegister
from med.models import Medicine

from guide.models import guides

import csv
import pandas as pd 
import numpy as np 
from sklearn.linear_model import LinearRegression


import random
#email
import smtplib, ssl


from io import BytesIO
from django.http import HttpResponse
from django.template.loader import get_template

from xhtml2pdf import pisa

from django.http import HttpResponse
from django.views.generic import View

import pdfkit
import pytz
import datetime


# from practice.decorator import status
from plotly.offline import plot
from plotly.graph_objs import Scatter

import pdfkit
def createGraph(request):
    bills = SK_Bills.objects.all()
    bills_store = list(set([b.store_person for b in bills]))
    bills_products = list(set([b.pd_nm for b in bills]))
    if request.POST:
        s=request.POST["store"]
        p=request.POST["product"]
        bills_requested = SK_Bills.objects.filter(store_person=ChemistRegister.objects.get(
            cid=s), pd_nm=p).order_by('-date_data')

        bill_store_date_reuested, bills_store_quantity_requested = [], []
        [[bill_store_date_reuested.append(b.date_data.year), bills_store_quantity_requested.append(
            b.pd_qty)] for b in bills_requested]

        s1, s2 = pd.Series(bill_store_date_reuested), pd.Series(
            bills_store_quantity_requested)
        df = pd.DataFrame({'a': s1, 'b': s2})

        df = df.groupby(df['a'])['b'].agg(['sum'])
        bill_store_date_reuested, bills_store_quantity_requested = list(
            df.index), list(df["sum"])

        if (len(bills_store_quantity_requested) == 0):
            no_date = True
        else:
            no_date = False

        plot_div, data = None, None
        if not no_date:
            data = [[bill_store_date_reuested[i], bills_store_quantity_requested[i]]
                    for i in range(len(bills_store_quantity_requested))]
            model = LinearRegression()
            model.fit(np.array(bill_store_date_reuested).reshape(
                -1, 1), np.array(bills_store_quantity_requested).reshape(-1, 1))
            year = np.array(int(request.POST["year"])).reshape(-1, 1)

            predicted = model.predict(
                np.array(year).reshape(-1, 1))
            if predicted[0][0]<0:
                predicted[0][0]=0
            data.append([year[0][0], round(int(predicted[0][0]))])

            bill_store_date_reuested.append(year[0][0])
            bills_store_quantity_requested.append(int(predicted[0][0]))

            plot_div = plot([Scatter(x=bill_store_date_reuested, y=bills_store_quantity_requested,
                                     mode='lines', name='test',
                                     opacity=0.8, marker_color='green')],
                            output_type='div')
            print(bill_store_date_reuested[1])
        return render(request, 'admin/newgraph.html', {'year':year ,'s':s,'p':p,'no_data': no_date, 'store': bills_store, 'product': bills_products, 'plot_div': plot_div, 'data': data})
    return render(request, 'admin/newgraph.html', {'store': bills_store, 'product': bills_products})


# User signin 
def signin(request):
    if request.POST:
        email = request.POST['uid']
        pass1 = request.POST['userpwd']
        try:
            valid = UserRegister.objects.get(uid=email,userpwd=pass1)
            if valid:
                request.session['user'] = email
                return redirect('user:adminDashboard')
            else:
                return render(request,'error.html')
        except:
            return render(request,'error.html')
    return render(request,'signin1.html')

#User logout
def logout(request):
    if 'user' in request.session.keys():
        del request.session['user']
        return redirect('user:index')
    return redirect('user:index')

#User index
def index(request):

    return render(request,'index.html')

#User Index{This indexpage will open after doing signin}
def index1(request):
    if 'user' in request.session:
        qur=UserQueryForm(request.POST)
        if qur.is_valid():
            qur.save()
            messages.success(request,'Message sent..')
        return render(request,'index1.html',{'qur':qur})
    else:
        return redirect('user:signin')


# User register
def signup(request):
    obj=UserRegisterForm(request.POST)
    
    if obj.is_valid():
        obj.save()
        return HttpResponseRedirect('/signin/')
    return render(request,'signup.html',{'obj':obj})
    

# User can search for medicines using this function
def search(request):
    try:
        serch = request.GET.get('query')
    except:
        serch = None
    if  serch:
        med = guides.objects.all().filter(Q(mname__icontains= serch) | Q(drug__icontains = serch) | Q(symptoms__icontains = serch) | Q(diseases__icontains = serch) )
        data = {
            'med':med
        }
    else:
        data={}
    return render(request,'search1.html',data)

# Forgot Password

def forgot_pass(request):
    email = request.POST.get('email')
    request.session['username'] = email
    if email == None:
        return render(request,'email.html')
        
    print(email)
    otp = ''
    rand = random.choice('0123456789')
    rand1 = random.choice('0123456789')
    rand2 = random.choice('0123456789')
    rand3 = random.choice('0123456789')
    otp = rand + rand1 + rand2 + rand3
    print(otp)
    request.session['otp'] = otp


    port = 465
    context = ssl.create_default_context()
    server = smtplib.SMTP_SSL("smtp.gmail.com",port,context=context)
    server.login("UphaRProjecT@gmail.com","uphar007")
    server.sendmail("UphaRProjecT@gmail.com",email,otp)
    server.quit()
    return redirect('user:otpcheck')
        

    return render(request,'email.html')

def otpcheck(request):
    if request.session.has_key('otp'):
        otp = request.session['otp']
        try:
            otpobj = request.POST.get('otp')
            if otpobj == None:
                return render(request,'otp.html')
            if otp == request.POST.get('otp'):
                return redirect('user:newpassword')
            else:
                return HttpResponse("<a href = ''>Wrong OTP Entered.</a>")
        except:
            return redirect('user:signin')
    return render(request,'otp.html')

def newpassword(request):
    new_pass = request.POST.get('password')
    if request.method == 'POST':
        obj = UserRegister.objects.get(uid = request.session['username'])
        obj.userpwd = new_pass
        obj.save()
        return redirect('user:signin')
    return render(request,'forgotpassword.html')
#Add to cart 



def add_to_cart(request):
    if 'user' in request.session:
        data = request.session['user']
        ur = UserRegister.objects.get(uid=data)
        context={}
        items = cart.objects.filter(user = ur)
        context['items'] = items
        context['users'] = ur

        if request.method == "POST":
            mid = request.POST["mid"]
            qty = request.POST["qty"]
            # data = request.user.id
            is_exist =  cart.objects.filter(medicine__id = mid,user = ur,status= False)
            if len(is_exist)>0:
                context['msz'] = "Alredy in your cart"
                context['cls'] = "alert alert-warning"
            else:
                medicine = get_object_or_404(guides,id=mid)
                # usr = get_object_or_404(UserRegister,id=request.user.id)
                c = cart(user=ur ,medicine = medicine, quantity=qty)
                c.save()
                context['msz'] = "Added in your cart"
                context['cls'] = "alert alert-success"
              
        return render(request,'cart.html',context)
    else:
        return redirect('logout')

def get_cart_data(request):
    if 'user' in request.session:
        data = request.session['user']
        ur = UserRegister.objects.get(uid=data)
        items =  cart.objects.filter(user=ur, status=False)
        total,quantity = 0,0
        for i in items:
            total += float(i.medicine.package_price)*i.quantity
            quantity += float(i.quantity)

        res = {
            "Total":total, 
            "quan":quantity
        }
        return JsonResponse(res)
    else:
        return redirect('logout')

def change_quan(request):
    if "quantity" in request.GET:
        cid = request.GET["cid"]
        qty = request.GET["quantity"]
        cart_obj = get_object_or_404(cart,id=cid)
        cart_obj.quantity = qty
        cart_obj.save()
        return HttpResponse(cart_obj.quantity )
    
    if "delete_cart" in request.GET:
        id =request.GET["delete_cart"]
        cart_obj = get_object_or_404(cart,id=id)
        cart_obj.delete()
        return HttpResponseRedirect('/cart/')


def AdminDashboard(request):
    if request.session.has_key('user'):
        auser = request.session['user']

        model = ChemistRegister.objects.all()
        # predict_graph()

        # print(today.month)
        data = {}
        try:
            q = request.GET.get('search')
        except:
            q = None
        if q:
            product = ChemistRegister.objects.filter(
                Q(StoreName__icontains=q) | Q(PersonName__icontains=q))
            data = {
                'data': model,
                'StoreDetails': product,
                'auser': auser
                # 'des': dealer
            }
        else:
            data = {'data': model}
        return render(request, 'admin/dashboard.html', data)
    else:

Invento-A Pharmacy Management_final/Uphar 2/User_Master/templates/allbill.html
{% load static %}
<!DOCTYPE html>
<!-- Designined by CodingLab | www.youtube.com/codinglabyt -->
<html lang="en" dir="ltr">

<head>
    <meta charset="UTF-8">
    <!--<title> Responsiive Admin Dashboard | CodingLab </title>-->
    <link rel="stylesheet" type="text/css" href="{% static 'css/box.css' %}">
    <!-- Boxicons CDN Link -->
    <link href='https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css' rel='stylesheet'>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>

<body>
    <div class="sidebar">
        <div class="logo-details">
            <i class='bx bxl-c-plus-plus'></i>
            <span class="logo_name">NeoPharmacy</span>
        </div>
        <ul class="nav-links">
            
            <li>
                <a href="{% url 'user:adminDashboard' %}" class="active">
                    <i class='bx bx-grid-alt'></i>
                    <span class="links_name">Dashboard</span>
                </a>
            </li>
            <li>
                <a href="{% url 'user:confirm_order' %}">
                    <i class='bx bx-box'></i>
                    <span class="links_name">order-list</span>
                </a>
            </li>
            <li>
                <a href="{% url 'user:allbill' %}">
                    <i class='bx bx-box'></i>
                    <span class="links_name">All Bills</span>
                </a>
            </li>
            <li>
                <a href="{% url 'user:createGraph' %}">
                  <i class='bx bx-box' ></i>
                  <span class="links_name">Prediction</span>
                </a>
              </li>
            
            <li class="log_out">
                <a href="{% url 'user:logout' %}">
                    <i class='bx bx-log-out'></i>
                    <span class="links_name">Log out</span>
                </a>
            </li>
        </ul>
    </div>
    <section class="home-section">
        <nav>
            <div class="sidebar-button">
                <i class='bx bx-menu sidebarBtn'></i>
                <span class="dashboard">Dashboard</span>
            </div>

        </nav>
        
        <div class="home-content">
        <div class="overview-boxes">
            <div class="box">
                <div class="right-side">
                    <a style="text-decoration: none;color: rgb(116, 116, 241);" href="{% url 'user:adminDashboard' %}">Dashboard</a>
                 
                </div>
        
              </div>     

        </div>
    
        
            
                <table style=" width:50%; height: fit-content; margin-left: 50px; text-align: center; box-shadow: 3px 2px 1px rgb(34, 4, 82); background-color: white;">
                            <thead style="margin: 5px; padding: 10px;">
                                <tr>
                                    <th style="text-align: center;font-weight: bold; padding:5px; margin-left:60px;"> chemist name </th>
                                    <th style="text-align: center;font-weight: bold; padding:5px; margin-left:60px;"> chemist Email </th>
                                    <th style="text-align: center;font-weight: bold; padding:5px; margin-left:60px;"> Bill no </th>
                                    <th style="text-align: center;font-weight: bold; padding:5px; margin-left:60px;"> Bill Date </th>
                                    <th style="text-align: center;font-weight: bold; padding:5px; margin-left:60px;"> action </th>
                                    
                                </tr>
                            </thead>
                            <tbody >
                                {% for i in pdBill %}

                                <tr>
                                    <td>{{ i.name }}</td>
                                    <td>{{ i.email }}</td>
                                    <td>{{ i.Billno }}</td>
                                    <td>{{ i.billdate }}</td>
                                    <td><a href="{% url 'chemist:SK_View_Bills' i.Billno %}">view</a></td>

                                    {% comment %} {% if j.show %}
                                    <td><a href="{% url 'create_pdf' i %}">Bill Data</a></td>
                                    {% else %}
                                    <td><a href="{% url 'user:billdata' i %}">Bill Data</a></td>
                                    {% endif %} {% endcomment %}
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    

        </div>
    </section>

                        

Invento-A Pharmacy Management_final/Uphar 2/User_Master/templates/cart.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" >
    <title>Add To wishlist</title>
    <style>
        .cart td{
            width: 10px;
        }
    </style>
</head>
<body><div class="col-md-8 mx-auto">
   <h1>Welcome : <I> {{ users.userfname }} {{ users.usermname }} {{ users.userlname }}</I></h1>
    {% if status %}
    <h1>{{status}}</h1>
{% else %}
    <!-- <h1 id = "mycart">My Cart ({{items|length}})</h1> -->
    <h1>My wishlist(<span id = "mycart"></span>)</h1>
{% endif %}

        {% if msz%}
        <div class="{{cls}} mt-3"><h3>{{msz}}</h3></div>
        {% endif %}
    </div>
        <table class="table cart">
            <thead>
                <tr>
                    <th><I> Medicine Name</I></th>
                    <th><I> Drug Name</I></th>
                    <th><I> Quantity</I></th>
                    <th><I> Price </I></th>
                </tr>
            </thead>
            <tbody>
                {% for i in items %}
                <tr  id="row{{i.id}}">
                    <td>{{i.medicine.mname}}</td>
                    <td>{{i.medicine.drug}}</td>
                    <td>
                         <div class="row">
                            <div class="col-md-3">
                                <i class="btn btn-primary" onclick="change_quan('{{i.id}}','plus')">&#43;</i>
                            </div>
                            <div class="col-md-6">
                                <input  value="{{i.quantity}}" class="form-control" id="cart{{i.id}}">
                                </div>
                            <div class="col-md-3">
                                <i class="btn btn-primary" onclick="change_quan('{{i.id}}','minus')">&#45;</i>
                            </div>
                        </div>
                    
                    </td>
                    <td>{{i.medicine.package_price}}</td>
                    <td><button onclick="remove_cart('{{i.id}}')" class="btn btn-danger">&times; Remove</button></td>
                </tr>
                {% endfor %}
            </tbody>
</table>

<div class="col-md-3 my-5">
    <div style="box-shadow:0px 0px 10px gray;">
   <table class="table cart ">
     <tr>
         <td><I> TOTAL</I></td>
         <td id="item_total"></td>
     </tr>
     
     <tr>
         <td><I> Quantity</I></td>
         <td id="quantity"></td>
     </tr>
        </table>
        <a class="btn btn-primary " href="{% url 'user:Userindex' %}"><h4>search More Medicine</h4></a>
</div>
<script>
    function grandtotal(){
        $.ajax({
            url:"{% url 'user:cartData' %}",
            type:'get',
            success:function(data){
                $("#item_total").html("&#8377;"+Math.round(data.Total))
                $("#quantity").html(data.quan+" Items")
                $("#mycart").html(data.quan)
            }
        })
    }
    grandtotal(); 
    function change_quan(id,action){
        let old = $("#cart"+id).val();
        quan = 0
        if(action=="plus"){
               quan += parseInt(old)+1
           }else{
               quan += parseInt(old)-1
           }
           $("#cart"+id).val(quan); 

           $.ajax({
               url:"{% url 'user:changeData' %}",
               type:"get",
               data:{cid:id, quantity:quan},
               success:function(data){
                        grandtotal();
                        if(data==0){
                            remove_cart(id);               
                        }
                    }
           })
    }

    function remove_cart(id){
        $.ajax({
            url:"{% url 'user:changeData' %}",
            data:{delete_cart:id},
            success:function(data){
                grandtotal();
                $("#row"+id).hide();
            }

        })
    }
</script>
    </body>
</html>

Invento-A Pharmacy Management_final/Uphar 2/User_Master/templates/email.html
<html>
    <body>
        <h1>{{otp}}</h1>
        <form method="POST">
            {% csrf_token %}
            <input type="email" id="id_user_name" name="email" value="{{ email }}" placeholder="Enter Email Id">
            <br>
            <button type="submit">Send Otp</button>
        </form>
    </body>
</html>

Invento-A Pharmacy Management_final/Uphar 2/User_Master/templates/error.html
<!-- purple x moss 2020 -->

<head>
    <link href="https://fonts.googleapis.com/css2?family=Nunito+Sans:wght@600;900&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/4b9ba14b0f.js" crossorigin="anonymous"></script>
    <style>
        body {
  background-color: #95c2de;
}

.mainbox {
  background-color: #95c2de;
  margin: auto;
  height: 600px;
  width: 600px;
  position: relative;
}

  .err {
    color: #ffffff;
    font-family: 'Nunito Sans', sans-serif;
    font-size: 11rem;
    position:absolute;
    left: 20%;
    top: 8%;
  }

.far {
  position: absolute;
  font-size: 8.5rem;
  left: 42%;
  top: 15%;
  color: #ffffff;
}

 .err2 {
    color: #ffffff;
    font-family: 'Nunito Sans', sans-serif;
    font-size: 11rem;
    position:absolute;
    left: 68%;
    top: 8%;
  }

.msg {
    text-align: center;
    font-family: 'Nunito Sans', sans-serif;
    font-size: 1.6rem;
    position:absolute;
    left: 16%;
    top: 45%;
    width: 75%;
  }

a {
  text-decoration: none;
  color: white;
}

a:hover {
  text-decoration: underline;
}
    </style>
  </head>
  <body>
    <div class="mainbox">
      <div class="err">:(</div>
      <div class="msg">Maybe you enter the wrong Password OR Username please enter the correct one<p>Let's go <a href="{% url 'user:index' %}">home</a> and try from there.</p></div>
        </div>

Invento-A Pharmacy Management_final/Uphar 2/User_Master/templates/signup.html
{% load static %}
<html>
                <head>
                
                        <link rel="stylesheet" type="text/css" href="{% static 'css/register1.css' %}">
        
                </head>
    <body>
            <form  method="POST" class="box">
                {% csrf_token %}
                
                
                    <div class="login-wrap">
                        <div class="login-html">
   
                               <center> <input id="tab-1" type="radio" name="tab" class="sign-in" checked><label for="tab-1" class="tab">SIGN UP</label></center>
                                
                                <div class="login-form">

                                        <div class="sign-up-html">
                                                <div class="group">
                                                       
                                                        <label for="user" type="Email" class="label">Email</label>
                                                        <input id="id_uid" type="text" name="uid" class="input" value="{{ uid }}" style="color: cornsilk;" >
                                                </div>
                                                <div class="group">
                                                        <label for="pass" type="password" class="label" data-type="password">Password</label>
                                                        <input id="id_userpwd" type="password" name="userpwd" class="input" value="{{ userpwd }}">
                                                        
                                                </div>

                                                <div class="group">
                                                        <label for="pass" type="text" class="label" data-type="password">Password hint</label>
                                                        <input id="id_userpwd" type="text" name="forgot_pass" class="input" value="{{ forgot_pass }}">
                                                        
                                                </div>

                                                <div class="group">
                                                        <label for="pass" class="label">First Name</label>
                                                        <input id="id_userfname" type="text" name="userfname" class="input" value="{{ userfname }}">
                                                </div>
                                                <div class="group">
                                                        <label for="pass" class="label">Middle Name</label>
                                                        <input id="id_usermname" type="text" name="usermname" class="input" value="{{ usermname }}">
                                                </div>
                                                <div class="group">
                                                        <label for="pass" class="label">Last Name</label>
                                                        <input id="id_userlname" type="text" name="userlname" class="input" value="{{ userlname }}">
                                                </div>
                                                <div class="group">
                                                        <label for="pass" class="label">Address</label>
                                                        <input id="id_useraddress" type="text" name="useraddress" class="input" value="{{ useraddress }}">
                                                </div>
                                                <div class="group">
                                                        <label for="pass" class="label">City</label>
                                                        <input id="id_usercity" type="text" name="usercity" class="input" value="{{ usercity }}">
                                                </div>
                                                <div class="group">
                                                        <label for="pass" class="label">Area</label>
                                                        <input id="id_userarea" type="text" name="userarea" class="input" value="{{ userarea }}">
                                                </div>
                                                <div class="group">
                                                        <label for="pass" class="label">Pincode</label>
                                                        <input id="id_userpincode" type="text" name="userpincode" class="input" value="{{ userpincode }}">
                                                </div>
                                                <div class="group">
                                                        <label for="pass" class="label">Contact_No</label>
                                                        <input id="id_usercontactno" type="text" name="usercontactno" class="input" value="{{ usercontactno }}">
                                                </div>
                                                <div class="group">
                                                        <input type="submit" class="button" value="Sign Up" href="{% url 'user:signin' %}" style="border: 2px solid #2ecc71;">
                                                </div>
                                                <div class="hr"></div>
                                                <div class="foot-lnk">
                                                        <label for="tab-1"><a href="{% url 'user:signin' %}" style="color: teal;">Already Member?</a>
                                                </div>
                                        </div>
                                </div>
                        </div>
                </div>     
        
            </form>
    </body>
</html>