Invento-A Pharmacy Management_final/Uphar 2/Chemist_Master/urls.py
from django.urls import path
from Chemist_Master.views import SK_Create_Pdf,SK_View_Bills,Dashboard,DeleteProduct,EditProduct,ProductListView,order_medicine,chemist_index,chemist_signup,chemist_signin,query,Uploaded_Medi,update_med,delete_med,logout,forgot_pass,otpcheck,newpassword,order_medicine

urlpatterns = [
    # signin,signup,indexpage
    path('signin/',chemist_signin,name="ch_signin"),
    path('signup/',chemist_signup,name="ch_signup"),
    path('',chemist_index,name="ch_index"),
    #Chemist interactions with medicines
    path('Uploaded_Medi/',Uploaded_Medi,name='Uploaded_Medi'),
    path('update_med/<int:id>',update_med,name='update_med'),
    path('delete_med/<int:id>',delete_med,name='delete_med'),
    path('order-medicine/',order_medicine,name='order-medicine'),
    path('productlist/', ProductListView, name='ProductListView'),
    path('dashboard/', Dashboard, name='Dashboard'),
    path('query/', query, name='query'),

    path('deleteproduct/<int:id>', DeleteProduct, name='deleteproduct'),
    path('editproduct/<int:id>', EditProduct, name='editproduct'),
    
    #Logout
    path('logout/',logout,name='logout'),
    
    # Forgot Password
    path('forgot_pass/',forgot_pass,name="forgotpass"),
    path('otpcheck/',otpcheck,name="otpcheck"),
    path('newpassword/',newpassword,name="newpassword"),
    path('View_Bills/<str:ids>', SK_View_Bills, name='SK_View_Bills'),
    path('SK_create_pdf/<str:dt>',SK_Create_Pdf, name='sk_create_pdf'),

    
]

Invento-A Pharmacy Management_final/Uphar 2/Uphar/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(('User_Master.urls','user'))),
    path('guide/',include(('guide.urls','guide'))),
    path('med/',include(('med.urls','med'))),
    path('Chemist_Master/',include(('Chemist_Master.urls','chemist'))),
]

Invento-A Pharmacy Management_final/Uphar 2/med/urls.py
from django.urls import path
from med import views
from .views import Search
urlpatterns = [
  
    path('add/', views.medi,name='add'),
    path('show/',views.show1,name='show'),
    path("search/<str:para>/",views.show, name="profilesearch"),
    path("search/", Search.as_view(), name="searchpage"),
    path('update/<int:id>', views.update),  
    path('delete/<int:id>', views.destroy), 
]

Invento-A Pharmacy Management_final/Uphar 2/Chemist_Master/models.py
from django.db import models


# Chemist Details
class ChemistRegister(models.Model):
    cid=models.EmailField(max_length=50,verbose_name='Email')
    chemistpwd=models.CharField(max_length=20,verbose_name='Password')
    chemistfname=models.CharField(max_length=20,default='',verbose_name='First_Name')
    chemistmname=models.CharField(max_length=20,default='',verbose_name='Middle_Name')
    chemistlname=models.CharField(max_length=20,default='',verbose_name='Last_Name')
    chemistaddress=models.CharField(max_length=20,default='',verbose_name='Address')
    chemistcity=models.CharField(max_length=20,default='',verbose_name='City')
    chemistarea=models.CharField(max_length=20,default='',verbose_name='Area')
    chemistpincode=models.IntegerField(default='',verbose_name='Pincode')
    chemistcontactno=models.IntegerField(default='',verbose_name='Contact_No')
    chemistphoto = models.FileField(upload_to = 'upload',verbose_name='store certificate',null=True,blank=True)
    forgot_pass = models.CharField('Write your password hint',max_length=100,default='')
    def __str__(self):
        return self.cid


## ------changes--------##
class StoreDetails(models.Model):
    StoreName = models.CharField(max_length = 50,blank = True)
    PersonName = models.CharField(max_length = 50,blank = True)
    Contact = models.IntegerField(blank = True)
    email = models.EmailField(blank = True, default="", max_length=150)
    password = models.CharField(max_length = 50)
    add1 = models.TextField(default="")

    def __str__(self):
        return self.StoreName


class StockDetails(models.Model):
    productName = models.CharField(max_length = 50,blank = True)
    quantity = models.IntegerField()
    price = models.FloatField()

    def __str__(self):
        return self.productName

class ProductDetails(models.Model):
    store_person = models.ForeignKey('ChemistRegister',on_delete=models.CASCADE, null=True)
    productname = models.CharField(max_length = 50,default="")
    productquantity = models.IntegerField()
    date = models.DateField(auto_now=False,blank=True,null=True)
    status = models.BooleanField(default=False)
    isDeny = models.BooleanField(default=False)
    Bills_id = models.CharField(max_length = 200,default="",null=True,blank=True)

    def __str__(self):
        return self.productname


class SK_Bills(models.Model):
    store_person = models.ForeignKey('ChemistRegister',on_delete=models.CASCADE, null=True)
    Bill_No = models.CharField(max_length = 200,default="")
    pd_nm = models.CharField(max_length = 200,default="")
    pd_price = models.FloatField(default=0.0)
    pd_qty = models.IntegerField(default=0)
    pd_tot = models.FloatField(default=0.0)
    date_data = models.DateField(auto_now=False,blank=True,null=True)
    
    def __str__(self):
        return self.Bill_No

Invento-A Pharmacy Management_final/Uphar 2/Chemist_Master/forms.py
from django import forms
from Chemist_Master.models import ChemistRegister
from  guide.models import guides

class ChemistRegisterform(forms.ModelForm):
    class Meta:
        model=ChemistRegister
        fields='__all__'

class guideForm(forms.ModelForm):
    class Meta:
        model = guides
        fields = "__all__"

Invento-A Pharmacy Management_final/Uphar 2/Chemist_Master/views.py
from django.shortcuts import render,redirect
from django.http import request,HttpResponseRedirect,HttpResponse
from Chemist_Master.models import *
from User_Master.models import *
from med.models import Medicine
from med.forms import MedicineForm
from Chemist_Master.forms import ChemistRegisterform,guideForm
from guide.models import guides
from django.core.paginator import Paginator
from datetime import date
import random
#email
import smtplib, ssl,pandas 
from .models import SK_Bills,ChemistRegister

from io import BytesIO
from django.http import HttpResponse
from django.template.loader import get_template

from xhtml2pdf import pisa

from django.http import HttpResponse
from django.views.generic import View
from plotly.offline import plot
from plotly.graph_objs import Scatter

import pdfkit

#Chemist signin page
def chemist_signin(request):
    if request.method=="POST":
        print(request.POST['cid'])
        try:
            m = ChemistRegister.objects.get(cid=request.POST['cid'])
            if m.chemistpwd == request.POST['chemistpwd']:
                request.session['user'] = m.cid
                return redirect('chemist:ch_index')
            else:
                return render(request,'error.html')
        except:
            return render(request,'error.html')
    return render(request,'chemist_signin1.html')

# Showing uploaded medicines by chemist
def Uploaded_Medi(request):
    
    if 'user' in request.session:
        med = guides.objects.all()
        paginator = Paginator(med, 5) # Show 10 medicines per page.
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        return render(request,'test.html',{'med':med,'page_obj': page_obj})
    else:
        return redirect('chemist:ch_signin')

            
  # Update medicine {done by chemist}   
def update_med(request,id):
    if 'user' in request.session:
        medi = guides.objects.get(id=id)  
        form = guideForm(request.POST or None, instance = medi)  
        if form.is_valid():  
            form.save()  
            return redirect('chemist:Uploaded_Medi')
        return render(request,'edit.html', {'medi': medi}) 
    else:
        return redirect('chemist:ch_signin')
 
# delete medicine{done by chemist}
def delete_med(request,id):
    med = guides.objects.get(id=id)
    med.delete()
    return redirect('chemist:Uploaded_Medi')
    
# Chemist module home page
def chemist_index(request):
    if 'user' in request.session:
        return render(request,'chemist_index.html')
    else:
        return redirect('chemist:ch_signin')
        
# chemist signup
def chemist_signup(request):
    obj=ChemistRegisterform(request.POST,request.FILES)
    if obj.is_valid():
        obj.save()
        return redirect('chemist:ch_signin')
    return render(request,'chemist_signup.html',{'obj':obj})

#chemist logout
def logout(request):
    if 'user' in request.session:
        del request.session['user']
        return redirect('chemist:ch_signin')
    else:
        return redirect('chemist:ch_signin')
#chemist forgotpassword

def forgot_pass(request):
    email = request.POST.get('email')
    request.session['username'] = email
    if email == None:
        return render(request,'email.html')
        
    print(email)
    otp = ''
    rand = random.choice('0123456789')
    rand1 = random.choice('0123456789')
    rand2 = random.choice('0123456789')
    rand3 = random.choice('0123456789')
    otp = rand + rand1 + rand2 + rand3
    print(otp)
    request.session['otp'] = otp


    port = 465
    context = ssl.create_default_context()
    server = smtplib.SMTP_SSL("smtp.gmail.com",port,context=context)
    server.login("mailtesting681@gmail.com","mailtest@123")
    server.sendmail("mailtesting681@gmail.com",email,otp)
    server.quit()
    return redirect('chemist:otpcheck')
    return render(request,'email.html')

def otpcheck(request):
    if request.session.has_key('otp'):
        otp = request.session['otp']
        try:
            otpobj = request.POST.get('otp')
            if otpobj == None:
                return render(request,'otp.html')
            if otp == request.POST.get('otp'):
                return redirect('chemist:newpassword')
            else:
                return HttpResponse("<a href = ''>Wrong OTP Entered.</a>")
        except:
            return redirect('chemist:ch_signin')
    return render(request,'otp.html')

def newpassword(request):
    new_pass = request.POST.get('password')
    if request.method == 'POST':
        obj = ChemistRegister.objects.get(cid = request.session['username'])
        obj.chemistpwd = new_pass
        obj.save()
        return redirect('chemist:ch_signin')
    return render(request,'forgotpassword.html')

def order_medicine(request):
    username = request.session['user']
    print(username)
    store = ChemistRegister.objects.get(cid=username)
    prods = StockDetails.objects.all()
    if request.POST:
        pro_data = request.POST['productname']
        pro_qty = request.POST['productquantity']
        prod_date = request.POST['data']
        obj = ProductDetails()
        obj.store_person = store
        pro_nm = StockDetails.objects.get(id=int(pro_data))
        obj.productname = pro_nm.productName
        obj.productquantity = pro_qty
        obj.date = prod_date
        obj.save()
        return redirect('chemist:ProductListView')
    return render(request, 'store/addproduct.html', {'username': username, 'prods': prods})

def query(request):
      if request.POST:
        obj = UserQuery()
        obj.name=request.POST['name']
        obj.email=request.POST['email']
        obj.subject=request.POST['subject']
        obj.message=request.POST['message']
        obj.save()
        return redirect('chemist:ch_index') 
def ProductListView(request):
    if request.session.has_key('user'):
        username = request.session['user']
        store = ChemistRegister.objects.get(cid=username)
        model = ProductDetails.objects.filter(store_person=store)
        return render(request, 'store/productlist.html', {'data': model, 'username': username})
    else:
        return redirect('chemist:ch_signin')


def DeleteProduct(request, id):
    if request.session.has_key('user'):
        username = request.session['user']
        obj = ProductDetails.objects.get(id=id)
        obj.delete()
        return redirect('chemist:ProductListView')
    else:
        return redirect('chemist:ch_signin')


def EditProduct(request, id):
    if request.session.has_key('user'):
        username = request.session['user']
        model = ProductDetails.objects.get(id=id)
        # form = ProductDetailsForm(request.POST, instance=model)
        if request.POST:
            model.productname=request.POST['productname']
            model.productquantity=request.POST['productquantity']
            model.save()
            return redirect('chemist:ProductListView')
        return render(request, 'store/editproduct.html', {'data': model, 'username': username})
    else:
        return redirect('chemist:ch_signin')

class ProductViewData():
    def __init__(self, name, date, status):
        self.name = name
        self.date = date
        self.status = status

def getStatusInStr(isStatus, isDeny):
    if isStatus == True:
        return "Accepted"
    else:
        if isDeny == True:
            return "Denied"
        return "Pending"

def Dashboard(request):
    if request.session.has_key('user'):
        username = request.session['user']
        store = ChemistRegister.objects.get(cid=username)

        pdBill = SK_Bills.objects.filter(store_person=store)
        Bcount = 0
        bset = set()
        for i in pdBill:
            bset.add(str(i.Bill_No))

        print(bset)
        bset = list(bset)
        # bset.sort()
        print(bset)

        model = ProductDetails.objects.filter(store_person=store).count()
        today_stock = ProductDetails.objects.filter(
            store_person=store, date=date.today())
        qty = 0
        today_date = date.today
        print(today_date)

        acceptedData = ProductDetails.objects.filter(store_person=store)
        acceptedData = map(lambda product: ProductViewData(getattr(product, 'productname'), getattr(product, 'date'), getStatusInStr(getattr(product, 'status'), getattr(product, 'isDeny'))), acceptedData)

        for i in today_stock:
            qty += i.productquantity
        return render(request, 'store/dashboard.html', {'acceptedData' : acceptedData, 'bset': bset, 'Bcount': len(bset), 'data': model, 'total': qty, 'date': today_date, 'username': username})
    else:
        return redirect('chemist:ch_signin')

def SK_View_Bills(request, ids):
    print(ids)
    pdBill = SK_Bills.objects.filter(Bill_No=ids)
    tot = 0.0
    date = ""
    sperson = ''
    for i in pdBill:
        date = i.date_data
        sperson = i.store_person
        tot += float(i.pd_tot)
    return render(request, 'store/SK_Order_Bill.html', {'billNo': ids, 'sperson': sperson, 'ddate': date, 'tot': tot, 'BillDes': pdBill})

def render_to_pdf(template_src, context_dict={}):
    template = get_template(template_src)
    html = template.render(context_dict)
    result = BytesIO()
    pdf = pisa.pisaDocument(BytesIO(html.encode("ISO-8859-1")), result)
    if not pdf.err:
        return HttpResponse(result.getvalue(), content_type='application/pdf')
    return None



def SK_Create_Pdf(request, dt):
    if request.session.has_key('user'):
        # username = request.session['user']
        pdBill = SK_Bills.objects.filter(Bill_No=dt)
        for i in pdBill:
            k=i.store_person
        store = ChemistRegister.objects.get(cid=k)

        tot = 0.0
        date = ""
        sperson = ''
        for i in pdBill:
            date = i.date_data
            sperson = i.store_person
            tot += float(i.pd_tot)

        Order_Data = {}

        obj_data = SK_Bills.objects.filter(Bill_No=dt)

        prod_price = 0

Invento-A Pharmacy Management_final/Uphar 2/Chemist_Master/templates/store/addproduct.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  
  <head>
  
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Online Medical Facility</title>
    
    <link rel="stylesheet" type="text/css" href="{% static 'css/font-awesome.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/my.css' %}">
  
  <style>
    #banner{
	background: url('/static/img/DO.jpg') no-repeat fixed;
	background-size: cover;
	min-height: 690px;
	position: relative;
}


</style>
</head>


<body id="myPage" data-spy="scroll" data-target=".navbar" data-offset="60">
  <!--banner-->
  <section id="banner" class="banner">
    <div class="bg-color">
      <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
          <div class="col-md-12">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
				        <span class="icon-bar"></span>
				        <span class="icon-bar"></span>
				        <span class="icon-bar"></span>
				      </button>
              <!-- <a class="navbar-brand" href="#"><img src="{% static 'img/logo.png' %}" class="img-responsive" style="width: 140px; margin-top: -16px;"></a> -->
            </div>
            <div class="collapse navbar-collapse navbar-right" id="myNavbar">
              <ul class="nav navbar-nav">
                <li class=""><a href="#banner">Home</a></li>
                <li class=""><a href="#service">Services</a></li>
                
                <li class="active"><a href="{% url 'chemist:order-medicine' %}">order-medicine</a></li>
                <li class=""><a href="{% url 'chemist:Dashboard' %}">My-Dashboard</a></li>
                <li class=""><a href="{% url 'chemist:Uploaded_Medi' %}">Uploaded Medicine</a></li>
                <li class=""><a href="/guide/csv/">Medicine Guide</a></li>
                <li class=""><a href="#about">About</a></li>
                <!-- <li class=""><a href="#testimonial">Testimonial</a></li> -->
                <li class=""><a href="#contact">Contact</a></li>
                
                <li class=""><a class="" href="{% url 'chemist:logout' %}">Logout</a>
                  
                </ul>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </nav>
    <div class="container">
      <div class="row">
        <div class="banner-info">
          <div class="banner-logo text-center">
            <!-- <img src="{% static 'img/logo.png' %}" class="img-responsive"> -->
          </div>
          <center style="box-shadow: 1px 1px 1px 1px white;">
            
              <h1  style="text-decoration: underline;" class="title">order your medicine </h1><br>
          <form method="POST" onsubmit="alert('Product Added successfully');">
              {% csrf_token %}
              <!-- <div class="form-group">
                
                <input type="text" placeholder="Enter Product Name" class="form-control" name="productname" id="id_productname" style="width: 40%;">
              </div> -->
              <div class="form-group">
                
                <!-- <input type="text" placeholder="Enter Product Name" class="form-control" name="productname" id="id_productname" style="width: 40%;"> -->
                  <select name="productname" style="width: 40%; height: 40px; text-align: center;">
                  {% for i in prods %}
                  <option value="{{ i.id }}"> {{ i.productName }}</option>
                  {% endfor %}
                </select>
              </div>
              
              <div class="form-group" >
                <br>
                <input type="date" name="data">

                <input  type="number" placeholder="Enter Medicine quantity" class="form-control" name="productquantity" id="id_productquantity" style="width: 40%; text-align: center; padding: 8px; ">
              </div>
              <br>
              <br>
              <button type="submit" class="btn btn-success" style="padding: 5px;">Order Medicine</button>
            </form> </center>
            <div class="banner-text text-center">
              <!-- <h1 class="white">Medicine at your desk!!</h1> -->
              
            </div>
            <div class="overlay-detail text-center">
              <a href="#service"><i class="fa fa-angle-down"></i></a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!--/ banner-->
  
 
 
 
 
 
 
 
 
 
  <div class="icon-info">
  <!--service-->
  <section id="service" class="section-padding">
    <div class="container">
      <div class="row">
        <div class="col-md-4 col-sm-4">
          <h2 class="ser-title">Our Service</h2>
          <hr class="botm-line">
          <p >User can see the location of chemist store where the medicines are available,User can see the details of medicine with categories and drug-name.
The user gets a doctor's reference.
</p>
        </div>
        <div class="col-md-4 col-sm-4">
          <div class="service-info">
            <div class="icon">
              <i class="fa fa-stethoscope"></i>
            </div>
            <div class="icon-info">
              <h4>24 Hour Support</h4>
              <p >User can see the details of medicine 24 hours,<br>The user gets a doctor's reference,User can find the medicine in medical store 24 hours. </p>
            </div>
          </div>
          <div class="service-info">
            <div class="icon">
              <i class="fa fa-ambulance"></i>
            </div>
            <div class="icon-info">
              <h4>Emergency Services</h4>
              <p >In the case of emergency user can find medicine quickly and get the Doctor reference.</p>
            </div>
          </div>
        </div>
        <div class="col-md-4 col-sm-4">
          <div class="service-info">
            <div class="icon">
              <i class="fa fa-user-md"></i>
            </div>  
            <h4>Medical Counseling</h4>
            <p>User can see the details of medicine with categories and drug-name and know about the use of medicine.
The user gets a doctor's reference.</p>                
</div>
</div>  

      </div>    
    </div>  
  </section>  
  <!--/ service-->
 
  <!--about-->
  <section id="about" class="section-padding">
    <div class="container">
      <div class="row">
        <div class="col-md-3 col-sm-4 col-xs-12">
          <div class="section-title">
            <h2 class="head-title lg-line">The Medilap <br>Ultimate Dream</h2>
            <hr class="botm-line">
            <p class="sec-para"  >To promote awareness of healthcare among all section of indian people.</p>
            <a href="" style="color: #0cb8b6; padding-top:10px;">Know more..</a>
          </div>  
        </div>  
        <div class="col-md-9 col-sm-8 col-xs-12">
          <div style="visibility: visible;" class="col-sm-9 more-features-box">
            <div class="more-features-box-text">
              <div class="more-features-box-text-icon"> <i class="fa fa-angle-right" aria-hidden="true"></i> </div>
              <div class="more-features-box-text-description">
                <h3>AIM 1</h3>
                <p >To promote awareness among functionaries involved in Health and Hospital Management. To promote research in the field of Health and Hospital Management.</p>
              </div>  
            </div>  
            <div class="more-features-box-text">
              <div class="more-features-box-text-icon"> <i class="fa fa-angle-right" aria-hidden="true"></i> </div>
              <div class="more-features-box-text-description">
                <h3>AIM 2</h3>
                <p>Making health facility safe in emergency.</p>
              </div>  
            </div>  
          </div>  
        </div>  
      </div>  
    </div>  
  </section>  
  <!--/ doctor team-->

  <!--/ testimonial-->
  <!--cta 2-->
  <section id="cta-2" class="section-padding">
    <div class="container">
      <div class=" row">
        <div class="col-md-2"></div>
        <div class="text-right-md col-md-4 col-sm-4">
          <h2 class="section-title white lg-line">« A few words<br> about us »</h2>
        </div>  
        <div class="col-md-4 col-sm-5">
          Driven by creativity and innovation, we strive for excellence and to make a difference in the world of pharmaceuticals and healthcare.
           <p class="text-right text-primary"><i>— Uphar Healthcare</i></p>
        </div>   
        <div class="col-md-2"></div>
      </div>  
    </div>  
  </section>  
  <!--cta-->
  <!--contact-->
  <section id="contact" class="section-padding">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h2 class="ser-title">Contact us</h2>
          <hr class="botm-line">
        </div>  
        <div class="col-md-4 col-sm-4">
          <h3>Contact Info</h3>
          <div class="space"></div>
          <p><i class="fa fa-map-marker fa-fw pull-left fa-2x"></i>321, ---<br> ---, India </p>
          <div class="space"></div>
          <p><i class="fa fa-envelope-o fa-fw pull-left fa-2x"></i>uphar@gmail.com</p>
          <div class="space"></div>
          <p><i class="fa fa-phone fa-fw pull-left fa-2x"></i>+444 62357352</p>
        </div>  
        <div class="col-md-8 col-sm-8 marb20">
          <div class="contact-info">
            <h3 class="cnt-ttl">Having Any Query!</h3>
            <div class="space"></div>
            <div id="sendmessage">Your message has been sent. Thank you!</div>
            <div id="errormessage"></div>
            <form action="{% url 'chemist:query' %}" method="post" role="form" class="contactForm">
              {% csrf_token %}
              <div class="form-group">
                <input type="text" name="name" class="form-control br-radius-zero" id="name" placeholder="Your Name" data-rule="minlen:4" data-msg="Please enter at least 4 chars" />
                <div class="validation"></div>
              </div>  
              <div class="form-group">
                <input type="email" class="form-control br-radius-zero" name="email" id="email" placeholder="Your Email" data-rule="email" data-msg="Please enter a valid email" />
                <div class="validation"></div>
              </div>  
              <div class="form-group">
                <input type="text" class="form-control br-radius-zero" name="subject" id="subject" placeholder="Subject" data-rule="minlen:4" data-msg="Please enter at least 8 chars of subject" />
                <div class="validation"></div>
              </div>  
              <div class="form-group">
                <textarea class="form-control br-radius-zero" name="message" rows="5" data-rule="required" data-msg="Please write something for us" placeholder="Message"></textarea>
                <div class="validation"></div>
              </div>  

              <div class="form-action">
                <button type="submit" class="btn btn-form">Send Message</button>
              </div>  
            </form>  
          </div>  
        </div>  
      </div>  
    </div>  
  </section>  
  <!--/ contact-->
  <!--footer-->
  <footer id="footer">
    <div class="top-footer">
      <div class="container">
        <div class="row">
          <div class="col-md-4 col-sm-4 marb20">
            <div class="ftr-tle">
              <h4 class="white no-padding">About Us</h4>
            </div>  
            <div class="info-sec">
              <p> Driven by creativity and innovation, we strive for excellence and to make a difference in the world of pharmaceuticals and healthcare.
              </div>  
          </div>    
          <div class="col-md-4 col-sm-4 marb20">
            <div class="ftr-tle">
              <h4 class="white no-padding">Quick Links</h4>
            </div>  
            <div class="info-sec">
              <ul class="quick-info">
                <li><a href="#"><i class="fa fa-circle"></i>Home</a></li>
                <li><a href="#service"><i class="fa fa-circle"></i>Service</a></li>
                <li><a href="#contact"><i class="fa fa-circle"></i>Query</a></li>
              </ul>  
            </div>  
          </div>  
          <div class="col-md-4 col-sm-4 marb20">
            <div class="ftr-tle">
              <h4 class="white no-padding">Follow us</h4>
            </div>  
            <div class="info-sec">
              <ul class="social-icon">
                <li class="bglight-blue"><i class="fa fa-facebook"></i></li>
                <li class="bgred"><i class="fa fa-google-plus"></i></li>
                <li class="bgdark-blue"><i class="fa fa-linkedin"></i></li>
                <li class="bglight-blue"><i class="fa fa-twitter"></i></li>
              </ul>  
            </div>  
          </div>  
        </div>  
      </div>  
    </div>  
    
  </footer>  
  <!--/ footer-->

  <script src="{% static 'js/jquery.min.js' %}"></script>
  <script src="{% static 'js/jquery.easing.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
  <script src="{% static 'js/custom.js' %}"></script>
  <script src="{% static 'contactform/contactform.js' %}"></script>

</body>  

</html>

Invento-A Pharmacy Management_final/Uphar 2/Chemist_Master/templates/store/profile.html
{% extends 'store/base.html' %}
{% load static %}
{% block content2 %}
<html>
 <head>
    <link rel="stylesheet" href="/static/css/profile.css" type="text/css">      
</head>
   
<body>
<form method="POST">
    {% csrf_token %}
  <label for="fname">Name</label>
  <input type="text" id="id_PersonName" name="PersonName" value="{{ shop.PersonName }}" placeholder="Your name..">

  <label for="email">Email</label>
  <input type="email" id="id_email" name="email" value="{{ shop.email }}" placeholder="Your email..">

  <label for="mobile">Mobile No</label>
  <input type="number" id="id_Contact" name="Contact" value="{{ shop.Contact }}" placeholder="Your mobile no..">

  <label for="address">Address</label>
  <input type="text" id="id_add1" name="add1" value="{{ shop.add1 }}" placeholder="Your address..">

  <label for="store">Store Name</label>
  <input type="text" id="id_StoreName" name="StoreName" value="{{ shop.StoreName }}" placeholder="Your store name..">

  <input type="submit" value="Save Change">
</form>

</body>
</html>
{% endblock %}