Invento-A Pharmacy Management_final/Uphar 2/Uphar/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(('User_Master.urls','user'))),
    path('guide/',include(('guide.urls','guide'))),
    path('med/',include(('med.urls','med'))),
    path('Chemist_Master/',include(('Chemist_Master.urls','chemist'))),
]

Invento-A Pharmacy Management_final/Uphar 2/med/urls.py
from django.urls import path
from med import views
from .views import Search
urlpatterns = [
  
    path('add/', views.medi,name='add'),
    path('show/',views.show1,name='show'),
    path("search/<str:para>/",views.show, name="profilesearch"),
    path("search/", Search.as_view(), name="searchpage"),
    path('update/<int:id>', views.update),  
    path('delete/<int:id>', views.destroy), 
]

Invento-A Pharmacy Management_final/Uphar 2/guide/models.py
from django.db import models

# Medicine Details 

class guides(models.Model):
    mname=models.CharField(null='False',verbose_name='Medicine_Name',max_length=30)
    symptoms = models.CharField(max_length=1000, null='False')
    diseases = models.CharField(max_length=1000,null='False')
    category=models.CharField(null='False',verbose_name='Type',max_length=50)
    unit=models.CharField(max_length=10,null='False',verbose_name='Unit')
    unit_price=models.FloatField(null='False',verbose_name='Unit_price')
    package_unit=models.CharField(max_length=10,null='False',verbose_name='Package_Unit')
    package_price=models.FloatField(null='False',verbose_name='Package_price')
    drug=models.CharField(max_length=20,null='False',verbose_name='Drug_Name')
    per_unit=models.CharField(max_length=10,null='False',verbose_name='per_unit')
    indication=models.CharField(max_length=100,verbose_name='Indication')
    contraindication=models.CharField(max_length=100,verbose_name='Containdication')
    caution=models.CharField(max_length=500,null='True',verbose_name='Caution')
    side_effect=models.CharField(max_length=500,null='True',verbose_name='Side-Effect')
    
    def __str__(self):
        return self.mname

Invento-A Pharmacy Management_final/Uphar 2/med/models.py
from django.db import models
from Chemist_Master.models import ChemistRegister

# Currently we did not used it
class Medicine(models.Model):
    chemist = models.ForeignKey(ChemistRegister,on_delete=models.CASCADE,default='')
    m_name=models.CharField(max_length=50)
    batch=models.CharField(max_length=30)
    mfg=models.CharField(max_length=30)
    quantity=models.IntegerField()
    rate=models.FloatField()
    amount=models.FloatField()
    formulation_CHOICES = [
    ('Syrup', 'Syrup'),
    ('Tablet', 'Tablet'),
    ('Injection', 'Injection'),
]
    formulation=models.CharField(max_length=150,choices=formulation_CHOICES)

    def __str__(self):
        return self.m_name

Invento-A Pharmacy Management_final/Uphar 2/med/forms.py
from django import forms
from med.models import Medicine
from guide.models import guides

class MedicineForm(forms.ModelForm):
    
    class Meta:
        model = Medicine
        fields = "__all__"

class searchForm(forms.Form):
    search = forms.CharField(max_length= 200,label = "Please Do search Here")


class guideForm(forms.ModelForm):
    class Meta:
        model = guides
        fields = "__all__"

Invento-A Pharmacy Management_final/Uphar 2/med/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.http import HttpResponse
from med.forms import MedicineForm
from med.models import Medicine
from .forms import searchForm,guideForm

from django import views
from Chemist_Master.models import ChemistRegister
# Create your views here.

# Using only on function def medi from this view.py

#used For adding new medicines 
def medi(request):
    form=guideForm(request.POST)
    if form.is_valid():
        form.save()
        return redirect('chemist:Uploaded_Medi')
    else:
        form = guideForm()
    return render(request,'medindex.html',{'form':form})

def show1(request):
    abc=Medicine.objects.all()
    return render(request,"show.html",{'a': abc})

def show(request,para):  
    
    medi = Medicine.objects.all() if para == None else Medicine.objects.filter(m_name__icontains = para) 
    form = searchForm(data = request.POST) 

    return render(request,"search.html",{'medi':medi,'form': form})  
  

def update(request, id):  
    medi = Medicine.objects.get(id=id)  
    form = MedicineForm(request.POST or None, instance = medi)  
    if form.is_valid():  
        form.save()  
        return redirect("/med/show")  
    return render(request,'edit.html', {'medi': form})  

def destroy(request, id):  
    medi = Medicine.objects.get(id=id)  
    medi.delete()  
    return redirect("/med/show")  

def mediProfileList(request,  para = None):
    abc=Medicine.objects.all() if para == None else Medicine.objects.filter(name__icontains = para)
    return render(request,'viewprofile.html',{'profiles' : abc})

class Search(views.View):

    def get(self, request, *args, **kwargs):
        form = searchForm(initial={'search' : ''})
        
        return render(request,'search.html',{'form': form})

    def post(self, request, *args, **kwargs):
        form = searchForm(data = request.POST)
        if form.is_valid():
            return redirect('med:profilesearch',para = form.cleaned_data['search'])   
        else:
            return render(request,'search.html',{'form': form})

Invento-A Pharmacy Management_final/Uphar 2/med/templates/edit.html
{% load static %}  
<!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>Index</title>  
    
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.min.css' %}"/>  
<style>
  body{
    background-image: url('/static/img/pill.jpg');
    
  }
  
  
  .h-tag {
  /* font-size: 30px;
  color: #fff;
  text-align: center;
  -webkit-animation: h-tag 1s ease-in-out infinite alternate;
  -moz-animation: h-tag 1s ease-in-out infinite alternate;
  animation: h-tag 1s ease-in-out infinite alternate; */
  padding-bottom: 30px;
  text-shadow: 1px 1px 2px black, 0 0 25px blue, 0 0 5px darkblue;
  color: white;
}

/* @-webkit-keyframes h-tag {
  from {
    text-shadow: 0 0 10px #1c8adb, 0 0 20px#1c8adb, 0 0 30px #1c8adb, 0 0 40px  #1c8adb, 0 0 50px#1c8adb, 0 0 60px#1c8adb, 0 0 70px #1c8adb;
  }
  
  to {
    text-shadow: 0 0 20px #fff, 0 0 30px #1316db, 0 0 40px#1316db, 0 0 50px#1316db, 0 0 60px #1316db, 0 0 70px#1316db, 0 0 80px#1316db;
  }
} */
.post-form{    
  background: rgb(0 0 0 / 82%);
    color: white;
    top: 50%;
    left: 50%;
    position: absolute;
    transform: translate(-50%,-50%);
    box-sizing: border-box;
    padding: 70px 30px;
}
.post-form input[type="text"], input[type="number"] , select[id = id_chemist], select[id="id_formulation"]
{
  padding: 5px;
  border: none;
    border-bottom: 1px solid #fff;
    border-top: 1px solid #fff;
    background: transparent;
    outline: none;
    color: azure;
    border-radius: 8%;
    border-top-left-radius: 10px;
    border-top-right-radius: 10px;
    border-bottom-right-radius: 10px;
    border-bottom-left-radius: 10px;
    font-size: 15px;
}
option{
  background-color: rgb(46, 46, 44);
}
.button
{
    border: none;
    outline: none;
    background: #1c8adb;
    font-size: 15px;
    border-radius: 8px;
    padding: 10px 24px;
    background-color: white; 
  color: black; 
  border: 2px solid #4ca8af;
}
.button:hover
{
    cursor: pointer;
    background: #4ca8af;
    color: rgb(250, 253, 249);
}

table {
  font-family: arial, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

td, th {
  
  text-align: center;
  padding: 8px;
}

tr:nth-child(even) {
  background-color: #dddddd;
}
</style> 
  </head>  
<body>  
  <form method="POST" class="box"> 
    {% csrf_token %}
    
 <!-- <h1 class="h3-tag">Add New Medicine</h1>
 {{form.as_p}} -->

 <h1 class="h3-tag">Update Medicine</h1>
<center>
  <table>
    
    <tr>
      <td>
     <label for="id_mname">Medicine_Name:</label> 
     <input type="text"  name="mname" maxlength="30" required id="id_mname" value="{{medi.mname}}">
    </td>
   <td>
     <label for="id_symptoms">Symptoms:</label> 
     <input type="text" name="symptoms" maxlength="1000" required id="id_symptoms"  value="{{medi.symptoms}}">
    </td>
   <td>
     <label for="id_diseases">Diseases:</label>
      <input type="text"  name="diseases" maxlength="1000" required id="id_diseases"  value="{{medi.diseases}}">
    </td>
    </tr>
 
    <tr>
        <td>
     <label for="id_category">Type:</label> 
     <input type="text" name="category" maxlength="50" required id="id_category"  value="{{medi.category}}">
    </td>
   <td>
     <label for="id_unit">Unit:</label>
      <input type="text" name="unit" maxlength="10" required id="id_unit"  value="{{medi.unit}}">
    </td>
   <td>
     <label for="id_unit_price">Unit_price:</label>
      <input type="number" name="unit_price" step="any" required id="id_unit_price"  value="{{medi.unit_price}}">
    </td>
    </tr>
   <tr>
    <td>
     <label for="id_package_unit">Package_Unit:</label> 
     <input type="text" name="package_unit" maxlength="10" required id="id_package_unit"  value="{{medi.package_unit}}">
    </td>
   <td>
     <label for="id_package_price">Package_price:</label> 
     <input type="number" name="package_price" step="any" required id="id_package_price"  value="{{medi.package_price}}">
    </td>
   <td>
     <label for="id_drug">Drug_Name:</label> 
     <input type="text" name="drug" maxlength="20" required id="id_drug"  value="{{medi.drug}}">
    </td>
    </tr>
   
    <tr>
      <td>
     <label for="id_per_unit">Per_unit:</label> 
     <input type="text" name="per_unit" maxlength="10" required id="id_per_unit"  value="{{medi.per_unit}}">
    </td>
   <td>
     <label for="id_indication">Indication:</label>
      <input type="text" name="indication" maxlength="100" required id="id_indication" value="{{medi.indication}}">
    </td>
   <td>
     <label for="id_contraindication">Containdication:</label>
      <input type="text" name="contraindication" maxlength="100" required id="id_contraindication"  value="{{medi.contraindication}}">
    </td>
    </tr>
    <tr>
      <td>
     <label for="id_caution">Caution:</label> 
     <input type="text" name="caution" maxlength="500" required id="id_caution"  value="{{medi.caution}}">
    </td>
   <td>
     <label for="id_side_effect">Side-Effect:</label>
      <input type="text" name="side_effect" maxlength="500" required id="id_side_effect"  value="{{medi.side_effect}}">
    </td>

    </tr>
    </table>
  </center>

    </form>

</body>
</html> 

Invento-A Pharmacy Management_final/Uphar 2/med/templates/medindex.html
<!-- <!DOCTYPE html>  

 <html lang="en"> 

<head>  
  
<meta charset="UTF-8">  
    
<title>Index</title>  
    
{% load static %}  
    
<link rel="stylesheet" href="{% static 'css/style.css' %}"/>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
  
<style>
  body{
    margin: 0;
    padding: 0;
    font-family: sans-serif;
    /* background-image:  url('/static/img/mypill.jpg'); */
    background: rgb(58, 58, 57);
  }

  .box input[type = "text"],input[type="number"],select[id = id_chemist],select[id="id_formulation"]{
    border:0;
    background-color: blanchedalmond;
    display: block;
    margin: 20px auto;
    text-align: center;
    border: 2px solid #3498db;
    padding: 10px 10px;
    width: 200px;
    outline: none;
    color: rgb(26, 25, 25);
    border-radius: 24px;
    transition: 0.25s;
  }
  .box{
            width:unset;
    padding:inherit;
  
  margin-bottom:initial;
    text-align: center;
    
   
  }
 
  /*.box{
  width: 500px;
  padding: 40px;
  min-height:345px;
  margin-bottom: 200px;
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%,-50%);
  
  text-align: center;
  height: 650px;

} */



  .box label[for=id_mname],label[for=id_symptoms],label[for=id_diseases],label[for=id_category],label[for=id_unit]
  ,label[for=id_unit_price],label[for=id_package_unit],label[for=id_package_price],label[for=id_drug]
  ,label[for=id_per_unit],label[for=id_indication],label[for=id_contraindication],label[for=id_caution],label[for=id_side_effect]{
               font-style: italic;
               font-family: Verdana, Geneva, Tahoma, sans-serif;
               color: black;
           }
.button
{
    border: none;
    outline: none;
    
    background: #1c8adb;
    
    font-size: 15px;
    border-radius: 8px;
    padding: 10px 24px;
    background-color: white; 
  color: black; 
  border: 2px solid #4ca8af;
}
.button:hover
{
    cursor: pointer;
    background: #4ca8af;
    color: rgb(250, 253, 249);
}
.h3-tag {
  /* font-size: 30px;
  color: #fff;
  text-align: center;
  -webkit-animation: h3-tag 1s ease-in-out infinite alternate;
  -moz-animation: h3-tag 1s ease-in-out infinite alternate;
  animation: h3-tag 1s ease-in-out infinite alternate; */
  padding-bottom: 30px;
  text-shadow: 1px 1px 2px black, 0 0 25px blue, 0 0 5px darkblue;
  color: white;
}

/* @-webkit-keyframes h3-tag {
  from {
    text-shadow: 0 0 10px #fff, 0 0 20px #fff, 0 0 30px #15e453, 0 0 40px  #15e453, 0 0 50px #15e453, 0 0 60px #15e453, 0 0 70px #15e453;
  }
  
  to {
    text-shadow: 0 0 20px #fff, 0 0 30px #ff4da6, 0 0 40px #ff4da6, 0 0 50px #ff4da6, 0 0 60px #ff4da6, 0 0 70px #ff4da6, 0 0 80px #ff4da6;
  }
} */
table {
  font-family: arial, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

td, th {
  
  text-align: center;
  padding: 8px;
}

tr:nth-child(even) {
  background-color: #dddddd;
}

</style>
</head>  

<body >  
  
<div class="book-appoinement">
  <center>
  
      
      <div class="bg-form">
          
        <form method="POST" class="box"> 
      {% csrf_token %}
      
  

   <h1 class="h3-tag">Add New Medicine</h1>
  <center>
    <table>
      
      <tr>
        <td>
       <label for="id_mname">Medicine_Name:</label> 
       <input type="text" class="form-control" name="mname" maxlength="30" required id="id_mname">
      </td>
     <td>
       <label for="id_symptoms">Symptoms:</label> 
       <input type="text"  class="form-control"name="symptoms" maxlength="1000" required id="id_symptoms">
      </td>
     <td>
       <label for="id_diseases">Diseases:</label>
        <input type="text" class="form-control" name="diseases" maxlength="1000" required id="id_diseases">
      </td>
      </tr>
   
      <tr>
          <td>
       <label for="id_category">Type:</label> 
       <input type="text" name="category" maxlength="50" required id="id_category">
      </td>
     <td>
       <label for="id_unit">Unit:</label>
        <input type="text" name="unit" maxlength="10" required id="id_unit">
      </td>
     <td>
       <label for="id_unit_price">Unit_price:</label>
        <input type="number" name="unit_price" step="any" required id="id_unit_price">
      </td>
      </tr>
     <tr>
      <td>
       <label for="id_package_unit">Package_Unit:</label> 
       <input type="text" name="package_unit" maxlength="10" required id="id_package_unit">
      </td>
     <td>
       <label for="id_package_price">Package_price:</label> 
       <input type="number" name="package_price" step="any" required id="id_package_price">
      </td>
     <td>
       <label for="id_drug">Drug_Name:</label> 
       <input type="text" name="drug" maxlength="20" required id="id_drug">
      </td>
      </tr>
     
      <tr>
        <td>
       <label for="id_per_unit">Per_unit:</label> 
       <input type="text" name="per_unit" maxlength="10" required id="id_per_unit">
      </td>
     <td>
       <label for="id_indication">Indication:</label>
        <input type="text" name="indication" maxlength="100" required id="id_indication">
      </td>
     <td>
       <label for="id_contraindication">Containdication:</label>
        <input type="text" name="contraindication" maxlength="100" required id="id_contraindication">
      </td>
      </tr>
      <tr>
        <td>
       <label for="id_caution">Caution:</label> 
       <input type="text" name="caution" maxlength="500" required id="id_caution">
      </td>
     <td>
       <label for="id_side_effect">Side-Effect:</label>
        <input type="text" name="side_effect" maxlength="500" required id="id_side_effect">
      </td>

      </tr>
      </table>
    </center>

        <a href="{% url 'chemist:Uploaded_Medi' %}" class="btn btn-outline-success" onclick="return confirm('Are you sure you want to add medicine?')">Submit</a>
        <a href="{% url 'chemist:Uploaded_Medi' %}" class="btn btn-outline-warning" style="background-color: cornsilk;" >Back</a>
      
      </form>
  

</center>

</body>  
</html>   -->





<html>
    <head>
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
 
        <style>
          
body {
  margin:0;
  padding:0;
  font-family: sans-serif;
  background: linear-gradient(#141e30, #243b55);
}

.login-box {
  position: absolute;
  top: 50%;
  left: 50%;
  width: 400px;
  margin-top: 290px;
  padding: 40px;
  transform: translate(-50%, -50%);
  background: rgba(0,0,0,.5);
  box-sizing: border-box;
  box-shadow: 0 15px 25px rgba(0,0,0,.6);
  border-radius: 10px;
}

.login-box h2 {
  margin: 0 0 30px;
  padding: 0;
  color: #fff;
  text-align: center;
}

.login-box .user-box {
  position: relative;
}

.login-box .user-box input {
  width: 100%;
  padding: 10px 0;
  font-size: 16px;
  color: #fff;
  margin-bottom: 30px;
  border: none;
  border-bottom: 1px solid #fff;
  outline: none;
  background: transparent;
}
.login-box .user-box label {
  position: absolute;
  top:0;
  left: 0;
  padding: 10px 0;
  font-size: 16px;
  color: #fff;
  pointer-events: none;
  transition: .5s;
}

.login-box .user-box input:focus ~ label,
.login-box .user-box input:valid ~ label {
  top: -20px;
  left: 0;
  color: #03e9f4;
  font-size: 12px;
}

.login-box form button {
    background: linear-gradient(#141e30, #243b55);
  position: relative;
  display: inline-block;
  padding: 10px 20px;
  color: #03e9f4;
  font-size: 16px;
  text-decoration: none;
  text-transform: uppercase;
  overflow: hidden;
  transition: .5s;
  margin-top: 40px;
  letter-spacing: 4px
}

.login-box button:hover {
  background: #03e9f4;
  color: #fff;
  border-radius: 5px;
  box-shadow: 0 0 5px #03e9f4,
              0 0 25px #03e9f4,
              0 0 50px #03e9f4,
              0 0 100px #03e9f4;
}

.login-box button span {
  position: absolute;
  display: block;
}

.login-box button span:nth-child(1) {
  top: 0;
  left: -100%;
  width: 100%;
  height: 2px;
  background: linear-gradient(90deg, transparent, #03e9f4);
  animation: btn-anim1 1s linear infinite;
}

@keyframes btn-anim1 {
  0% {
    left: -100%;
  }
  50%,100% {
    left: 100%;
  }
}

.login-box button span:nth-child(2) {
  top: -100%;
  right: 0;
  width: 2px;
  height: 100%;
  background: linear-gradient(180deg, transparent, #03e9f4);
  animation: btn-anim2 1s linear infinite;
  animation-delay: .25s
}

@keyframes btn-anim2 {
  0% {
    top: -100%;
  }
  50%,100% {
    top: 100%;
  }
}

.login-box button span:nth-child(3) {
  bottom: 0;
  right: -100%;
  width: 100%;
  height: 2px;
  background: linear-gradient(270deg, transparent, #03e9f4);
  animation: btn-anim3 1s linear infinite;
  animation-delay: .5s
}

@keyframes btn-anim3 {
  0% {
    right: -100%;
  }
  50%,100% {
    right: 100%;
  }
}

.login-box button span:nth-child(4) {
  bottom: -100%;
  left: 0;
  width: 2px;
  height: 100%;
  background: linear-gradient(360deg, transparent, #03e9f4);
  animation: btn-anim4 1s linear infinite;
  animation-delay: .75s
}

@keyframes btn-anim4 {
  0% {
    bottom: -100%;
  }
  50%,100% {
    bottom: 100%;
  }
}
a{
  margin-left: 90px;
    padding: 10px 16px;
    width: 90px;
}
        </style>
    </head>
    <body>
      <div class="login-box">
        <h2>ADD Medicine</h2>
        <!-- <div><a  href="{% url 'chemist:ch_index' %}" style=" margin-left : 100px ;color: white; background-color: black;">Back</a></div>         -->
    <form method="POST">
        {% csrf_token %}
      <div class="user-box">
        <input type="text" name="mname" required="">
        <label>Medicine_Name</label>
      </div>
      <div class="user-box">
        <input type="text"name="symptoms" required="">
        <label>Symptoms</label>
      </div>
      <div class="user-box">
        <input type="text" name="diseases" required="">
        <label>Diseases</label>
      </div>
      <div class="user-box">
        <input type="text" name="category" required="">
        <label>Type</label>
      </div>
      <div class="user-box">
        <input type="text" name="unit"required="">
        <label>Unit</label>
      </div>
      <div class="user-box">
        <input type="number" name="unit_price"  required="">
        <label>Unit_price</label>
      </div>
      <div class="user-box">
        <input type="text" name="package_unit" required="">
        <label>Package_Unit</label>
      </div>
      <div class="user-box">
        <input type="number" name="package_price" required="">
        <label>Package_price</label>
      </div>
      <div class="user-box">
        <input type="text" name="drug" required="">
        <label>Drug_Name</label>
      </div>
      <div class="user-box">
        <input type="text" name="per_unit" required="">
        <label>Per_unit</label>
      </div>
      <div class="user-box">
        <input type="text" name="indication" required="">
        <label>Indication</label>
      </div>
      <div class="user-box">
        <input type="text" name="contraindication" required="">
        <label>Containdication</label>
      </div>
      <div class="user-box">
        <input type="text" name="caution" required="">
        <label>Caution</label>
      </div>
      <div class="user-box">
        <input type="text" name="side_effect" required="">
        <label>Side-Effect</label>
      </div>
      
      <button class="button" type="submit">
        <span></span>
        <span></span>
        <span></span>
        <span></span>
          Submit
        </button> 
        <a href="{% url 'chemist:ch_index' %}" class="btn btn-outline-danger">
            <span></span>
          <span></span>
          <span></span>
          <span></span>
                Back</a>
    </form>
  </div>
</body>

  </html>

Invento-A Pharmacy Management_final/Uphar 2/med/templates/search.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>Records</title>  
     {% load static %}  
     
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>  
    <style>
        form.example input[type=text] {
  padding: 10px;
  font-size: 17px;
  border: 1px solid grey;
  float: left;
  width: 80%;
  background: #f1f1f1;
}

form.example button {
  float: left;
  width: 20%;
  padding: 10px;
  background: #2196F3;
  color: white;
  font-size: 17px;
  border: 1px solid grey;
  border-left: none;
  cursor: pointer;
}

form.example button:hover {
  background: #0b7dda;
}

form.example::after {
  content: "";
  clear: both;
  display: table;
}
    </style>
</head>  
<body>  

        <form  method="post" enctype="multipart/form-data" class="example">
            {% csrf_token %}
            {{ medi }}
            <input type="text" placeholder="Search.." name="search2">
            <button type="submit"><i class="fa fa-search"></i></button>
          </form>
        </form>
<table class="table table-striped table-bordered table-sm">  
    <thead class="thead-dark">  
    <tr>  
        <th><center>Medicine ID</center></th>  
        <th><center>Medicine Name</center></th>
        <th><center>Batch</center></th>
        <th><center>Mfg</center></th>  
        <th><center>Quantity</center></th>
        <th><center>Rate</center></th>  
        <th><center>Amount</center></th>  
        <th><center>Formulation</center></th>  
        <th><center>Action</center></th>
    </tr>  
    </thead>  
    <tbody>  

{% for medi in medi %}  
    <tr>  
        <td><center>{{ medi.m_id }}</center></td>  
        <td><center>{{ medi.m_name }}</center></td>
        <td><center>{{ medi.batch }}</center></td>
        <td><center>{{ medi.mfg }}</center></td>  
        <td><center>{{ medi.quantity }}</center></td>
        <td><center>{{ medi.rate }}</center></td>  
        <td><center>{{ medi.amount }}</center></td>  
        <td><center>{{ medi.formulation}}</center></td>
        <td>  
            <a href="/edit/{{ medi.id }}"><span class="glyphicon glyphicon-pencil" ><center>Update</span></a>&nbsp;&nbsp;||&nbsp;  
            <a href="/delete/{{ medi.id }}">Delete</center></a>  
        </td>  
    </tr>  
{% endfor %}  
    </tbody>  
</table>  
<br>  
<br>  
<center><a href="{% url 'med:add' %}" class="btn btn-primary">Add New Record</a></center>  
</body>  
</html>  

Invento-A Pharmacy Management_final/Uphar 2/med/templates/show.html
{% load static %}
<!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>Records</title>     
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <style>
        th{
            background-color: rgb(7, 150, 216);
        }
        a:hover{
            color: rgb(81, 235, 34);
        }
        td{
            color: black;
        }
    </style>
</head>  
<body>  
<center>
    
<table class="table table-striped table-bordered table-sm">  
    <thead class="thead-dark">  
    <tr>  

        <th><center>Medicine Name</center></th>
        <th><center>Batch</center></th>
        <th><center>Mfg</center></th>  
        <th><center>Quantity</center></th>
        <th><center>Rate</center></th>  
        <th><center>Amount</center></th>  
        <th><center>Formulation</center></th>  
        <th><center>Action</center></th>
    </tr>  
    </thead>  
    <tbody>  

{% for medi in a %}  
    <tr>  
 
        <td><center>{{ medi.m_name }}</center></td>
        <td><center>{{ medi.batch }}</center></td>
        <td><center>{{ medi.mfg }}</center></td>  
        <td><center>{{ medi.quantity }}</center></td>
        <td><center>{{ medi.rate }}</center></td>  
        <td><center>{{ medi.amount }}</center></td>  
        <td><center>{{ medi.formulation}}</center></td>
        <td>  
            <a href="/med/update/{{ medi.id }}"><span class="glyphicon glyphicon-pencil" ><center>Update</span></a>&nbsp;&nbsp;||&nbsp;  
            <a href="/med/delete/{{ medi.id }}">Delete</center></a>  
        </td>  
    </tr>  
{% endfor %}  
    </tbody>  
</table>  
<br>  
<br>  
<center><a href="{% url 'med:add' %}" class="btn btn-primary">Add New Record</a>&nbsp;&nbsp;&nbsp;&nbsp;</center>
</center>
</body>  
</html>  